### ISSUE TITLE
Add global support for output directory

### ISSUE THREAD

**Issue by bencardoen** [bencardoen/DataCurator.jl#4]
For file aggregation, it's arduous to specify output path in the name of the table/list. 

Add
```toml
[global]
outputdirectory="path"
```

For aggregation operations, then prefix the path to the table.
